package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALARM".
 */
@Entity
public class Alarm {
    private Long date;
    private String description;
    private Long lessonId;
    private String alarmType;
    private Boolean isRepeating;

    @Generated(hash = 1972324134)
    public Alarm() {
    }

    @Generated(hash = 458326403)
    public Alarm(Long date, String description, Long lessonId, String alarmType, Boolean isRepeating) {
        this.date = date;
        this.description = description;
        this.lessonId = lessonId;
        this.alarmType = alarmType;
        this.isRepeating = isRepeating;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getLessonId() {
        return lessonId;
    }

    public void setLessonId(Long lessonId) {
        this.lessonId = lessonId;
    }

    public String getAlarmType() {
        return alarmType;
    }

    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType;
    }

    public Boolean getIsRepeating() {
        return isRepeating;
    }

    public void setIsRepeating(Boolean isRepeating) {
        this.isRepeating = isRepeating;
    }

}
