package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LESSON".
 */
@Entity
public class Lesson {

    @Id(autoincrement = true)
    private Long id;
    private Integer unitCount;
    private String name;
    private String lessonEducatorName;
    private String lessonEducatorPic;
    private Long endOfTermDate;
    private Long midTermDate;
    private Integer midTermGrade;
    private Integer endOfTermGrade;
    private String description;

    @Generated(hash = 1669664117)
    public Lesson() {
    }

    public Lesson(Long id) {
        this.id = id;
    }

    @Generated(hash = 1212541055)
    public Lesson(Long id, Integer unitCount, String name, String lessonEducatorName, String lessonEducatorPic, Long endOfTermDate, Long midTermDate, Integer midTermGrade, Integer endOfTermGrade, String description) {
        this.id = id;
        this.unitCount = unitCount;
        this.name = name;
        this.lessonEducatorName = lessonEducatorName;
        this.lessonEducatorPic = lessonEducatorPic;
        this.endOfTermDate = endOfTermDate;
        this.midTermDate = midTermDate;
        this.midTermGrade = midTermGrade;
        this.endOfTermGrade = endOfTermGrade;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUnitCount() {
        return unitCount;
    }

    public void setUnitCount(Integer unitCount) {
        this.unitCount = unitCount;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLessonEducatorName() {
        return lessonEducatorName;
    }

    public void setLessonEducatorName(String lessonEducatorName) {
        this.lessonEducatorName = lessonEducatorName;
    }

    public String getLessonEducatorPic() {
        return lessonEducatorPic;
    }

    public void setLessonEducatorPic(String lessonEducatorPic) {
        this.lessonEducatorPic = lessonEducatorPic;
    }

    public Long getEndOfTermDate() {
        return endOfTermDate;
    }

    public void setEndOfTermDate(Long endOfTermDate) {
        this.endOfTermDate = endOfTermDate;
    }

    public Long getMidTermDate() {
        return midTermDate;
    }

    public void setMidTermDate(Long midTermDate) {
        this.midTermDate = midTermDate;
    }

    public Integer getMidTermGrade() {
        return midTermGrade;
    }

    public void setMidTermGrade(Integer midTermGrade) {
        this.midTermGrade = midTermGrade;
    }

    public Integer getEndOfTermGrade() {
        return endOfTermGrade;
    }

    public void setEndOfTermGrade(Integer endOfTermGrade) {
        this.endOfTermGrade = endOfTermGrade;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
