package database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ROLL_CALL".
 */
@Entity
public class RollCall {
    private Long date;
    private Integer weekNumber;
    private Long classId;
    private Long lessonId;
    private Boolean wasPresent;

    @Generated(hash = 1160210292)
    public RollCall() {
    }

    @Generated(hash = 622662885)
    public RollCall(Long date, Integer weekNumber, Long classId, Long lessonId, Boolean wasPresent) {
        this.date = date;
        this.weekNumber = weekNumber;
        this.classId = classId;
        this.lessonId = lessonId;
        this.wasPresent = wasPresent;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Integer getWeekNumber() {
        return weekNumber;
    }

    public void setWeekNumber(Integer weekNumber) {
        this.weekNumber = weekNumber;
    }

    public Long getClassId() {
        return classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public Long getLessonId() {
        return lessonId;
    }

    public void setLessonId(Long lessonId) {
        this.lessonId = lessonId;
    }

    public Boolean getWasPresent() {
        return wasPresent;
    }

    public void setWasPresent(Boolean wasPresent) {
        this.wasPresent = wasPresent;
    }

}
